### ISSUE TITLE
Integration with CKeditor

### ISSUE THREAD

**Issue by MatteoPistorello** [mimo84/bootstrap-maxlength#162]
Hi,
is there a way to make it works with CKeditor? Thanks in advance

**Comment by mimo84** [comment]
I don't think there is a 'direct' way to integrate it, since ck editor would actually work off an iFrame, therefore what you could do is to listen for change events, get the number of chars in the editor (different than the simple innerHTML length as it would have extra chars such as heading tags for example), then you take this number and you use it to populate a partially hidden textarea, where you insert the same number of chars to make the maxLength to show up. 
That's just an idea though, I haven't worked with CK Editor before.
